In [51]:
# Leetcode: Two Sum (1.)

def twoSum(nums, target):
    """
    :type nums: List[int]
    :type target: int
    :rtype: List[int]
    """
    mem = {}
    for i in range(len(nums)):
        if target - nums[i] in mem:
            return [mem[target - nums[i]], i]
        if nums[i] not in mem:
            mem[nums[i]] = i
    
print(twoSum([1,2,3,4,5], 6))

[1, 3]


In [55]:
# map applies function to every element of the iterable object

def f(x):
    return "a"

print(list(map(f, "abcdefg")))

['a', 'a', 'a', 'a', 'a', 'a', 'a']


In [ ]:
# Characters are represented by their unicode codes / A string is a stream of unicode codes

print(chr(127757))
print(ord("a"))
print(ord("A"))

print("---")

# UTF-8 encoding / decoding of strings (unicode code stream). The string is represented by a sequence of bytes (octets; 8-bits; 0-255) 

text = "Hello World"

print(list(text.encode('utf-8')))
print(len(text))

🌍
97
65
---
[72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100]
11


## Einops (einsum, rearrange, reduce)

In [44]:
import torch
from einops import einsum, rearrange, reduce

x = torch.rand(2, 3)
print(x)
y = 1/3 * torch.tensor([1,2,3])

print(einsum(y, x, 'i, j i -> j'))
print('---')
print(reduce(x, 'i j -> j', 'mean'))
print('---')
print(einsum(x, y, 'i j, k -> k i j'))
print('---')
print(rearrange(einsum(x, y, 'i j, k -> k i j'), 'i j k -> j (i k)'))

tensor([[0.1687, 0.1765, 0.7990],
        [0.1876, 0.8251, 0.3159]])
tensor([0.9729, 0.9285])
---
tensor([0.1781, 0.5008, 0.5575])
---
tensor([[[0.0562, 0.0588, 0.2663],
         [0.0625, 0.2750, 0.1053]],

        [[0.1124, 0.1176, 0.5327],
         [0.1251, 0.5501, 0.2106]],

        [[0.1687, 0.1765, 0.7990],
         [0.1876, 0.8251, 0.3159]]])
---
tensor([[0.0562, 0.0588, 0.2663, 0.1124, 0.1176, 0.5327, 0.1687, 0.1765, 0.7990],
        [0.0625, 0.2750, 0.1053, 0.1251, 0.5501, 0.2106, 0.1876, 0.8251, 0.3159]])
